### ISSUE TITLE
Information disclosure with Println leftover

### ISSUE THREAD

**Issue by tobru** [alexellis/inlets#101]
## Expected Behaviour

When starting the Inlets client with the option `--print-token=false` I would consider that the token isn't printed.

## Current Behaviour

In [`pkg/client/client.go`](https://github.com/alexellis/inlets/blob/master/pkg/client/client.go#L40) line 40 there is a unconditional `fmt.Println(headers)` which also prints the token. This then looks like this:

```
2019/10/01 12:12:54 Upstream: HIDDEN => HIDDEN
Welcome to inlets.dev! Find out more at https://github.com/alexellis/inlets

map[X-Inlets-Id:[HIDDEN] X-Inlets-Upstream:[HIDDEN] Authorization:[Bearer HIDDEN]]
time="2019-10-01T12:12:54Z" level=info msg="Connecting to proxy" url="wss://HIDDEN"
```

## Possible Solution

I would propose to remove this affected line completely as this looks like a debugging leftover. I'm happy to provide a PR to fix that.

## Steps to Reproduce (for bugs)

Start Inlets client with `--print-token=false` and see the token printed anyways.

## Context

This is an unintentional information disclosure and looks like a debugging leftover during Inlets development.

## Your Environment

* inlets version `inlets --version`

```
Version: 2.4.1
Git Commit: 5d9330c259b84d6957c6a5b291e5622263ec876d
```

**Comment by alexellis** [comment]
It looks like debug information, feel free to remove it.
