### ISSUE TITLE
Use crypto/subtle for constant time comparison of auth token

### ISSUE THREAD

**Issue by alexellis** [alexellis/inlets#109]
Use crypto/subtle for constant time comparison of auth token

https://golang.org/src/crypto/subtle/constant_time.go

## Current Behaviour

A regular string comparison is used

## Possible Solution

Alter this code

```
func (s *Server) tokenValid(req *http.Request) bool {
	auth := req.Header.Get("Authorization")
	return len(s.Token) == 0 || auth == "Bearer "+s.Token
}
```

Use something like`if subtle.ConstantTimeCompare([]byte(auth), []byte("Bearer "+a.Token)) == 0 {` instead.

## Merge criteria

Testing e2e to show auth still works as designed with a positive and negative test. Console output is fine. A unit test, if there is none already gets extra points and kudos.

**Comment by eddiezane** [comment]
I'll take this one.
