### ISSUE TITLE
[Question] Upstream is returning 301 and proxy returns the redirected URL

### ISSUE THREAD

**Issue by vanhalt** [alexellis/inlets#15]
Hello,

We are trying to use your program as a replacement for Ngrok. Right now we have a Rails application that redirects to` http://lvh.me:3000 `since we need that domain for the use of subdomains.

So basically this is what happened:

```
# Server side
sudo ./inlets -server=true -port=80 -token=$(cat token.txt) -gateway-timeout=25s
2019/02/19 22:43:46 Server token: aaaaaaaaaaaaaaaaaa
2019/02/19 22:43:46 Gateway timeout: 25.000000 secs
2019/02/19 22:44:09 Connecting websocket on 201.236.190.60:22359:
2019/02/19 22:44:09 wait for request
2019/02/19 22:44:23 [780a0b565347499c9003c3533ca42fd1] proxy REMOTE GET /
2019/02/19 22:44:23 [780a0b565347499c9003c3533ca42fd1] request written to websocket
2019/02/19 22:44:23 wait for request
2019/02/19 22:44:23 [780a0b565347499c9003c3533ca42fd1] waiting for response
2019/02/19 22:44:24 [780a0b565347499c9003c3533ca42fd1] wrote 87 bytes
```

and...:

```
# Client Side
 ./inlets -server=false -remote=REMOTE:80 -upstream=http://127.0.0.1:3000 -token=aaaaaaaa
2019/02/19 19:44:09 Upstream:  => http://127.0.0.1:3000
2019/02/19 19:44:09 connecting to ws://REMOTE:80/tunnel
2019/02/19 19:44:09 Connected to websocket: 192.168.1.233:36276
2019/02/19 19:44:23 [780a0b565347499c9003c3533ca42fd1] /
2019/02/19 19:44:23 [780a0b565347499c9003c3533ca42fd1] proxy => http://127.0.0.1:3000/
2019/02/19 19:44:24 [780a0b565347499c9003c3533ca42fd1] tunnel res.Status => 301 Moved Permanently 
2019/02/19 19:44:24 [780a0b565347499c9003c3533ca42fd1] 601 bytes
2019/02/19 19:45:05 [d5ce93dc2f0243969b7f6ea1da270d0d] /
2019/02/19 19:45:05 [d5ce93dc2f0243969b7f6ea1da270d0d] proxy => http://127.0.0.1:3000/
2019/02/19 19:45:05 [d5ce93dc2f0243969b7f6ea1da270d0d] tunnel res.Status => 301 Moved Permanently 
2019/02/19 19:45:05 [d5ce93dc2f0243969b7f6ea1da270d0d] 601 bytes
```
So we are stucked right now. Sorry for this being a real newbie question... if you can at least point us in the right direction that would be awesome.

Thanks in advance and great project!

**Comment by alexellis** [comment]
Thanks for your interest in inlets. What was the expected and actual result?

Alex

**Comment by alexellis** [comment]
@vanhalt please give instructions to reproduce whatever you are observing. It's unclear from your report.

```
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behaviour
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

## Current Behaviour
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->


## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Operating System and version (e.g. Linux, Windows, MacOS):

* Are you using Docker Swarm or Kubernetes?

* Link to your project or a code example to reproduce issue:

```

Perhaps you can fill out the template?

Alex

**Comment by vanhalt** [comment]
## Expected Behaviour
We are trying to use your program as a replacement for Ngrok. Right now we have a Rails application that redirects tohttp://lvh.me:3000since we need that domain for the use of subdomains.

So the expected behaviour is the following:
- Start inlets as a ´server´ in ´remote´ host
- Start inlets as a ´client´ in local host pointing to local Rails server
- Access on browser ´remote´ location and navigate Rails app through inlets supporting redirects.

## Current Behaviour
- Start inlets as a ´server´ in ´remote´ host
- Start inlets as a ´client´ in local host pointing to local Rails server
- Access on browser ´remote´ location and get redirected to URL given by Rails app:

```
# inlets client log
2019/03/14 15:08:23 [a0f1b45df0de411ea8826b4955a0a383] proxy => http://127.0.0.1:3000/
2019/03/14 15:08:23 [a0f1b45df0de411ea8826b4955a0a383] tunnel res.Status => 301 Moved Permanently 
2019/03/14 15:08:23 [a0f1b45df0de411ea8826b4955a0a383] 601 bytes
```

## Possible Solution
I believe that the inlets client should rewrite redirects to REMOTE host instead of redirecting to another domains. But dunno if it is the best solution.

## Steps to Reproduce (for bugs)
1. Start an inlets server with a token
2. Start an inlets client connected to a server
3. Start an application server that redirects from localhost to lvh.me domain
4. Get redirected to lvh.me and see that traffic doesn´t go anymore to REMOTE server

## Context


I am trying to access a Rails app through inlets and test webhooks.


## Your Environment
- Ubuntu 18.10
 ```
./inlets --version
Version: 0.6.1
Git Commit: 36b0f6cdc17e14f387649490f9a9a045af5d5d14
```

Hope this is detailed enough. I am still trying to make it work, so if I find something I will update this comment.

Thanks for your attention and sorry for taking to long to respond.

**Comment by alexellis** [comment]
Hi, thanks for taking time to write this up.

I think this may be covered by the 2.0 release.

I'm happy to re-open if there are still problems after testing the latest version.

Alex
