### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by pascalandy** [alexellis/inlets#16]
sha256sum:

```
head -c 16 /dev/urandom | sha256sum | cut -d" " -f1
```

Cheers!

**Comment by alexellis** [comment]
Hey can you provide a bit more detail please?

Hope you're good Andy :)

Alex

**Comment by alexellis** [comment]
I tried both `shasum` commands on Linux and it appeared to work?

**Comment by pascalandy** [comment]
Humm, iI tried and it didn't work here. This was in a custom alpine container I use all the time. Maybe it's because I need to install shasum as well? 

Anyways, it's working on your machine :) I'll close.

**Comment by alexellis** [comment]
On Alpine busybox you do need to use sha256sum, but MacOS / "Linux" usually has bash and `shasum`.

https://github.com/openfaas/cli.openfaas.com/blob/master/get.sh#L37

It's possible to figure this out, but it's a bit verbose ^

Thanks for trying out the project :+1:
