### ISSUE TITLE
Question: Difference between ngrok and inlet

### ISSUE THREAD

**Issue by jhnferraris** [alexellis/inlets#18]
Hello, this is a nice tool. I would like to ask though, what's the difference between using inlet vs using [ngrok](https://ngrok.com/)?

**Comment by RaviTezu** [comment]
The intro [section](https://github.com/alexellis/inlets#intro) of the README.md file has some information on this.

**Comment by alexellis** [comment]
Thanks @RaviTezu

**Comment by alexellis** [comment]
Derek close
