### ISSUE TITLE
Not support multiple clients with one server

### ISSUE THREAD

**Issue by mylxsw** [alexellis/inlets#24]
Not support multiple clients with one server

## Expected Behaviour

When we start 2 clients, the server will be able to distinguish which client to deal the request from user.

## Current Behaviour

If 2 clients connected to one server, then all traffic  will be proxied to the 2 client randomness.

## Possible Solution

The server distinguish the request by hostname, and the clients exchange it's upstream map with server, then server send the request to any clients could deal the request.

> Sorry for my terrible English 😂

**Comment by alexellis** [comment]
Can you try the latest release and see if this is still the case? The latest release has some synchronisation.

**Comment by mylxsw** [comment]
What I mean is not multiple user request, but multiple host node connected to server using websocket, and the server do not know swhich host node should handle the request.

Maybe this image will help you understand my question.

![](https://ssl.aicode.cc/Xnip2019-02-23_18-16-52.jpg)

**Comment by alexellis** [comment]
Thank you for the diagram I use them a lot and I find them really useful. 

In your example both nodes are resolving different subdomains and that data is published in the request from the inlets exit node. in this specific scenario that means that only one of the inlets clients needs to respond.

**Comment by mylxsw** [comment]
Yes, that's what I want to say.

**Comment by alexellis** [comment]
Please try the latest version and specifically map the dns address in the `-upstream` flag.

**Comment by alexellis** [comment]
Please see my comment from Feb.
