### ISSUE TITLE
[RFE] Comparison with SSH forwarding in documentation

### ISSUE THREAD

**Issue by woky** [alexellis/inlets#26]
I was reading documentation seeking comparison with SSH forwarding to find out benefits, but couldn't find any mention. Could you please compare inlets to SSH tunnels?

**Comment by alexellis** [comment]
Please see the [goals](https://github.com/alexellis/inlets#goals) of the project for a detailed breakdown.

If ssh tunnelling is sufficient for your use-case, it's also a good option.

Thanks for your interest.
