### ISSUE TITLE
Connection refused from inside internal network

### ISSUE THREAD

**Issue by martindekov** [alexellis/inlets#29]
I work in company which has network for internal use aka you need VPN(Global protect) enabled and guest network which is for public usage. Trying to expose my minikube OpenFaaS gateway service results in 
```
> ./inlets -server=false  -remote=<public_computer_ip>:80  -upstream=http://<minikube_ip>:31112
2019/02/25 01:40:10 Upstream:  => http://<minikube_ip>:31112
2019/02/25 01:40:10 connecting to ws://<public_computer_ip>:80/tunnel
panic: dial tcp <public_computer_ip>: connect: connection refused

goroutine 1 [running]:
main.main()
	/Users/alex/go/src/github.com/alexellis/inlets/main.go:87 +0x7a8
```

## Expected Behaviour

Expose my gateway OF Kubernetes service to be accessed from the public internet through the IP of my machine and the exposed port.

## Current Behaviour

I get `panic: dial tcp <public_computer_ip>: connect: connection refused`

## Possible Solution

Not sure.

## Steps to Reproduce (for bugs)

1. Get access to internal network (legally)
2. Deploy OpenFaaS with Minikube with Gateway exposed by default at port `31112`
3. Run `./inlets -server=false  -remote=<your_public_ip>:80  -upstream=http://<minikube_ip>:31112`
4. Get connection refused

## Context

I would like to replace `ngrok` with `inlets` since `ngrok` has the same problem with internal networks.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.09.0
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Are you using Docker Swarm or Kubernetes?
Kubernetes(Minikube)
* Link to your project or a code example to reproduce issue:
N/A steps to reproduce above

**Comment by alexellis** [comment]
What happened on the guest network?

Could you connect to your exit-node under any other circumstance and what TLD are you using for your domain?

Alex

**Comment by alexellis** [comment]
@martindekov

**Comment by martindekov** [comment]
Sorry alex for the late response, but was not in VMware office for the last 4 days will be today and will let you know what I did

**Comment by martindekov** [comment]
> What happened on the guest network?

No matter the network I tried them all(wifi guest/internal cable)

> Could you connect to your exit-node under any other circumstance and what TLD are you using for your domain?

Yep I can connect to http://127.0.0.1:31112/ or http://<minikube_ip>:31112/ and I don't use TLD, just direct IP.

> Connection refused generally means that the server was contactable but that it didn't have anything listening on the port?

I do the command as I pointed in the issue 
```
inlets -server=false  -remote=<public_computer_ip>:80  -upstream=http://<minikube_ip>:31112
```

I can access the OF Gateway through the upstream URL `http://<minikube_ip>:31112` but from my phone or computer I cant through my computer Ipv4 IP address

**Comment by martindekov** [comment]
I did not run `hash-brow` example as I needed the inlets as client between the OF gateway and telephone for example.

**Comment by alexellis** [comment]
Just to prove it's not the VMware network, can you try this at home?

**Comment by martindekov** [comment]
Ok, maybe I am doing something wrong, I get `bad handshake` now. Exact steps I do are
1. Two terminals No1. No2.
1.1 Terminal 1: `sudo inlets -server=true -port=80`
1.2 Terminal 2: `sudo inlets -server=false  -remote=188.124.78.43:80  -upstream=http://192.168.189.237:31112/`

I am exposing my minikube instance. What am I doing wrong? Disabled the gateway basic-auth before that I got the error mentioned in the issue above.

**Comment by martindekov** [comment]
With the `hash-browns`:

1. Open three terminals `No1` `No2` `No3`
2. Run `hash-browns` like pointed in docs `port=3000 go run server.go`
3. `curl` localhost:
```
> curl -d "hash this" http://127.0.0.1:3000/hash 
19467788bc0cf11790a075ea718452cecf0e79db59d1964670475e5fe2e4a611
```
4. Get public IP:
```
> curl https://ipinfo.io/ip
94.139.203.152
```
5. Run `inlets`:
```
./inlets -server=false  -remote=94.139.203.152:80 -upstream=http://127.0.0.1:3000/
2019/03/03 15:16:57 Upstream:  => http://127.0.0.1:3000/
2019/03/03 15:16:57 connecting to ws://94.139.203.152:80/tunnel
panic: dial tcp 94.139.203.152:80: connect: connection refused

goroutine 1 [running]:
main.main()
	/home/martindekov/go/src/github.com/alexellis/inlets/main.go:100 +0x855
```

Actually in here I noticed it just gives `connection refused` even without curling the endpoint. Note I made sure to erase every process running on port `:80`

**Comment by alexellis** [comment]
Hi @martindekov 

I think this is not working because you are getting the public IP of your work network connection, you need to use the IP of the exit node.

Set up an exit node using the scripts provided for DO or Scaleway.

Alex
