### ISSUE TITLE
Publish binary & Docker image upon git "release"

### ISSUE THREAD

**Issue by alexellis** [alexellis/inlets#31]
## Expected Behaviour

Upon creating a GitHub release Travis should be triggered to:
* publish and save binaries
* push a Docker image

## Current Behaviour

This is done manually.

## Possible Solution

Copy the approach of openfaas/faas-cli

The last step will require me to configure the Docker Hub push secret and GitHub releases secret, but the community can prepare 90% of the work. Copying the existing approach.

**Comment by alexellis** [comment]
Derek reopen

**Comment by hugomd** [comment]
I'm keen to pick this up @alexellis 👍 

Also, out of interest, what's the reasoning for using Alpine as the base image rather than 'scratch`?

**Comment by s8sg** [comment]
@hugomd I was already in it, expecting PR by today. If you wanna going to go ahead please give me a knock, I'll pick something else. :)

**Comment by hugomd** [comment]
@s8sg If you're already working on it then keep going at it! I'll find something else to do 👍

**Comment by alexellis** [comment]
Binary is now being released via: https://github.com/alexellis/inlets/releases/tag/0.5.6

**Comment by alexellis** [comment]
@hugomd 

> Also, out of interest, what's the reasoning for using Alpine as the base image rather than `scratch`?

I'm curious why you think `scratch` would be more suitable?

**Comment by hugomd** [comment]
@alexellis Typically `scratch` images are smaller than those based on Alpine, and if all we need from Alpine is the certificates we can add another stage to install the certificates and then copy them over to a scratch image. 🐳

**Comment by alexellis** [comment]
Alpine Linux is about as minimal as it gets (1MB as a compressed layer?), plus it's much cleaner to add the certs by using `apk`.

**Comment by alexellis** [comment]
Derek close: released
