### ISSUE TITLE
Consider replacing CMD with ENTRYPOINT?

### ISSUE THREAD

**Issue by dchaofei** [alexellis/inlets#35]
## Expected Behaviour
I hope to execute `docker run alexellis2/inlets -h` can output normally.

## Current Behaviour
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"-h\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled
```

## Possible Solution
Modify CMD to ENTRYPOINT in Dockerfile

**Comment by alexellis** [comment]
You need to run:

```bash
docker run alexellis2/inlets:0.5.4 ./inlets --help
```

I don't like `ENTRYPOINT` because it's so hard to override in derived images or for debugging. We need to put inlets in the `PATH` though so we can do:

```bash
docker run alexellis2/inlets:0.5.4 inlets --help
```

The latest tag is not published/updated btw.

**Comment by dchaofei** [comment]
thank you for your reply.

**Comment by alexellis** [comment]
Would you like to do a PR to `Dockerfile` so that we have `inlets` built into `/usr/local/bin/`?

**Comment by alexellis** [comment]
I've moved things to use `ENTRYPOINT` per your suggestion cc @LucasRoesler and also moved inlets into the `PATH` and made the Docker image non-root.
