### ISSUE TITLE
Docs: show example of inlets over SSH tunnel

### ISSUE THREAD

**Issue by alexellis** [alexellis/inlets#38]
## Expected Behaviour

Docs: show example of inlets over SSH tunnel

## Current Behaviour

inlets does not do link encryption unless it is fronted by a reverse-proxy with SSL enabled.

## Possible Solution

Document how to set up a port-forwarding ssh connection so that inlets can connect on 127.0.0.1 as the -remote address and use the default encryption  of ssh.

i.e.

```
ssh -N -L 8080:127.0.0.1:80

inlets -server=false -remote=ws://127.0.0.1:8080
```

**Comment by alexellis** [comment]
@hugomd want to take this?

**Comment by hugomd** [comment]
@alexellis I'll give it a go! 👍

**Comment by alexellis** [comment]
LMK if you have questions. It's just using the port-forwarded SSH connection instead of a remote port to establish the web-socket.

**Comment by alexellis** [comment]
Hi @hugomd we're about 4 weeks in now, are you still working on this? Do you need any help?

Alex
