### ISSUE TITLE
question about running this at home with 3 node topology.

### ISSUE THREAD

**Issue by gedw99** [alexellis/inlets#39]
Here is my proposed physical topology.

Topology:
1. Cloud Gateway Proxy
2. Home Gateway. Also running pihole. Just set the main router to use this node for DNS resolution.
3. Compute nodes -  raspberry pi's inside running all my stuff.

This allows all the Compute nodes to be 100% just doing what they do, without any reliance on the inlets code and also no chance of security slips.

Home gateway would run inlets but also have the golang pihole equivalent to harden it.
I use: https://github.com/looterz/grimd

Cloud Gateway could run on any cloud.

Looking forward to getting this setup and everyones comments and if this is also a setup others need.

**Comment by alexellis** [comment]
Sounds good. Let us know how you get on 👍
