### ISSUE TITLE
 Failed to connect on exit node running inlets from docker port 8005: but Connection refused

### ISSUE THREAD

**Issue by Hokutosei** [alexellis/inlets#48]
Failed to connect on exit node running inlets from docker port 8005: but Connection refused

## Expected Behaviour
should be able to access the exit node by inlet running inside docker

## Steps to Reproduce (for bugs)

1.  run inlet from Exit node via docker `docker run --rm -p 9020:9020 alexellis2/inlets:0.5.4 ./inlets server --port=9020 `
2. run inlet from Host node via docker `docker run -d alexellis2/inlets:0.5.4 ./inlets client --remote=<public_ip>:9020 --upstream=http://172.16.80.81:8005`
3. send http get to inlet to Exit node `curl -XGET http://<public IP>:9020/api/values -i`

## Context
I am evaluating solutions other than paid services.. please let me know If I missed some steps to run this? thank you!

## Your Environment

Exit Node:
- Docker version
```
docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
- Host
 ```
Linux azure01 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Host Node
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Host
```
MINGW64_NT-10.0 MSI 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys
```

- Local Http server
- A dotnet core serving in port `8005`

**Comment by alexellis** [comment]
Thanks for your interest in inlets.

Can you access http://172.16.80.81:8005 via a container? Normally your docker containers need need be on the same docker network then you can address them by DNS service discovery.

**Comment by Hokutosei** [comment]
@alexellis thank you for the response.. `http://172.16.80.81:8005` is the same network with my docker that runs inlet.. same problem with

`docker run -d alexellis2/inlets:0.5.4 ./inlets client --remote=<public_ip>:9020 --upstream=http://0.0.0.0:8005

**Comment by Hokutosei** [comment]
also, the weirdest part is, the response error `Failed to connect to <PUBLIC_IP> port 9020: Connection refused` after I do curl to my remote docker server running inlet.. this just means, server isn't really running..

but running inlets without docker, I can access it.
```
docker-user@azure01:~/tmp$ ./inlets server --port=9020
2019/03/13 07:44:48 Gateway timeout: 5.000000 secs
2019/03/13 07:44:52 [c2206168559e42cab06831ac01aabe14] proxy <PUBLIC_IP>:9020 GET /api/values
2019/03/13 07:44:52 [c2206168559e42cab06831ac01aabe14] waiting for response
2019/03/13 07:44:57 [c2206168559e42cab06831ac01aabe14] timeout after 5.000000 secs
```

**Comment by alexellis** [comment]
I don't think I was clear.

```
docker network create dev
docker run -d image_name --network=dev
docker run -d netcoreapp --network=dev
```

**Comment by alexellis** [comment]
I'm going the close the issue because there is no issue with inlets, this is a user-support question related only to networking configuration.

Feel free to keep commenting.

**Comment by Hokutosei** [comment]
thanks.. but I think I am not explaining my problem really well. will look on to this more..

**Comment by alexellis** [comment]
You can run inlets on your host or in a Docker container. If using Docker then you must use an IP or DNS entry for upstream that is accessible by the container in which it is running. I suspect that you have misconfigured your networking. @kenfdev is using a Docker image with OpenFaaS for instance.
