### ISSUE TITLE
Webrtc instead of websockets ?

### ISSUE THREAD

**Issue by gedw99** [alexellis/inlets#49]
There is a complete webrtc stack in golang.
The data channel would be more efficient that websockets and provide full duplex communication.

The other thing it does is remove the need for a cloud server for buddy coding or other P2P use cases. The cloud just sets the connection between the two peers and then is not needed.

This could then encapsulate http or other protocols 

The GitHub org is called pions.
It's very well supported also.

I think there is a demo of a webrtc tunnel floating around in GitHub too.
On mobile and in a rush right now.

**Comment by gedw99** [comment]
https://github.com/rtctunnel/rtctunnel

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Thanks for the suggestion. I'll look into webrtc when I get time, but for the time-being I think web sockets are going to be the way inlets works.

**Comment by alexellis** [comment]
https://github.com/AquiGorka/kanpo

https://github.com/rtctunnel/rtctunnel
