### ISSUE TITLE
etcd with inlets for discovery.

### ISSUE THREAD

**Issue by gedw99** [alexellis/inlets#50]
I am using weaver.
https://github.com/gojektech/weaver/

It runs on minikube and k8.
Its is a rL7 reverse proxy that can do Authorisation and route the calls down to the different Containers based on rules engines.
It uses Etcd for discovery of the containers
It does not need to be manually reloaded.

I am thinking of using it with inlets.
intlets can do the TLS ( CertMagic) and then forward requests to weaver server.
The weaver server then forwards to the containers.
BUT is there a hope that ETCD wil be usd by Inlets for its discovery.

Or maybe i should use OpenFAAS ? Does OpenFAAS have routing at L7 ?

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Hi @gedw99 using etcd for service discovery is not on the roadmap right now, but thanks for the suggestion.

Using Kubernetes for service discovery is something I've put on the roadmap however, which may be equivalent for you in due course? 

https://github.com/alexellis/inlets#stretch-goals

In the meantime I think you would possibly be able to use inlets with weaver where inlets is the exit node pointing at your weave instance within your private network. 

Alex
