### ISSUE TITLE
build dist: installsuffix not needed ?

### ISSUE THREAD

**Issue by gedw99** [alexellis/inlets#54]
see
https://plus.google.com/117192131596509381660/posts/eNnNePihYnK

**Comment by alexellis** [comment]
Hi thanks for your interest. If you're completely confident of this, then attempt a patch but please test the resulting binary in both Ubuntu and an Alpine container.

**Comment by joeblew99** [comment]
lets park it for doing later... Its not on the main line..

**Comment by alexellis** [comment]
@joeblew99 happy for you to work on this, it should take only a few minutes right?

I won't be able to get to it, so let me know if you want to cover it otherwise I'll close the issue to reduce noise.

Thanks again for using inlets.

**Comment by alexellis** [comment]
@gedw99 the Google Plus+ page is now down, @viveksyngh just took a look. Do you have other links?

**Comment by alexellis** [comment]
Closing: inactive, no response from author.
