### ISSUE TITLE
url query params being duplicated

### ISSUE THREAD

**Issue by mbarlow** [alexellis/inlets#57]
when using inlets 0.6.3, if a GET request comes through with query params they are duplicated.

## Expected Behaviour

query params should work normally

## Current Behaviour
?foo=bar becomes: ?foo=bar?foo=bar

## Steps to Reproduce (for bugs)

1. Follow instructions and run inlets on a server like digital ocean w/ caddy
2. run the client as specified in instructions: inlets client --remote wss://mydomaingoeshere.com --upstream=mydomaingoeshere.com=http://127.0.0.1:8080 --token=mytoken
3. open browser and goto: https://mydomaingoeshere.com/?foo=bar and look at the inlets client output
4. you will see a message: proxy => http://127.0.0.1:8080/?foo=bar?foo=bar

## Context

accessing get query params in handler code returns undesired results

## Your Environment

* inlets version `inlets --version` : 0.6.3

* Docker/Kubernetes version `docker version` / `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS): Mac OS

* Link to your project or a code example to reproduce issue:

**Comment by mbarlow** [comment]
removing lines: https://github.com/alexellis/inlets/blob/master/pkg/client/client.go#L138-L140 fixes the issue.

**Comment by alexellis** [comment]
Hi @mbarlow thanks for the report.

I found that those lines were needed to pass on the query string. Perhaps we need a unit test?

Have you tried the PR #53?

Alex

**Comment by alexellis** [comment]
@mbarlow how is this now with the 2.x release?

**Comment by carlosedp** [comment]
I've tested this on Inlets built from source and saw no duplication. All parameters sent from server, arrive on client.

**Comment by alexellis** [comment]
Thank you Carlos. I'll close it
