### ISSUE TITLE
Is cert-magic already implemented?

### ISSUE THREAD

**Issue by toxsick** [alexellis/inlets#58]
Hi Alex,

while playing around with inlets a little bit I was wondering if the initial project goal 

> - automatic TLS provisioning for endpoints using cert-magic

 is already implemented somehow? Currently not at all right?

Thanks for the awesome work!

regrads
Hannes

**Comment by alexellis** [comment]
Hi Hannes,

It's still on the roadmap however I did write instructions and s tutorial about how to do this with Caddy. https://github.com/alexellis/inlets/blob/master/README.md#how-do-i-enable-tls--https

Is this of help?

Alex

**Comment by toxsick** [comment]
Yeah I thought this is the case. This way I have to implement an extra logic on the server that configures caddy to also issue an certificate for every gateway domain of my inlets clients started with `--upstream  "gateway.mydomain.tk=http://127.0.0.1:3000"` right?

It would be super nice that when the client requests an upstream with a gateway domain the inlets server would then issue the certificate for that gateway domain automatically. Is this even the goal?

**Comment by toxsick** [comment]
Also [caddys license](https://caddyserver.com/products/licenses) prohibits me from using it, so i have to try something else

**Comment by alexellis** [comment]
@toxsick I often hear that people assume Caddy's license means that it cannot be used.

Caddy ships with Apache 2, is that a license you cannot use?

There is no need to use the pre-compiled binaries which can be licensed under other terms.

Does that make sense?

The example I showed with Caddy will also work with other reverse proxies such as Traefik. 

Alex

**Comment by alexellis** [comment]
https://github.com/mholt/caddy/blob/master/LICENSE.txt

**Comment by alexellis** [comment]
I'm going to close the issue since this is on the roadmap. For technical support, there is a channel in the OpenFaaS Slack.

--
Join Slack to connect with the community
https://docs.openfaas.com
