### ISSUE TITLE
Install script not working

### ISSUE THREAD

**Issue by diego-vieira** [alexellis/inlets#59]
When running `curl -sLS https://get.inlets.dev | sh` we get `Cannot GET /inlets/` because it's redirecting to `https://www.alexellis.io/inlets/`.

Maybe update the README to use `curl -sLS https://raw.githubusercontent.com/alexellis/inlets/master/get.sh | sudo sh` instead?

Thanks

**Comment by alexellis** [comment]
Hi thanks for letting me know.

I'll take a look at this soon. 

Alex

**Comment by alexellis** [comment]
Derek close: fixed DNS settings.
