### ISSUE TITLE
will you please add a --verbose command line options?

### ISSUE THREAD

**Issue by yunfan** [alexellis/inlets#61]
i am tring this tool from README
and i met some problem not sure if its my enviroment or the tools
so i think i need a --verbose options to let the service print all the debug info that i need

## Expected Behaviour

add a `--verbose or -v` commandline option 

## Your Environment

inlets x86 on server side 
inlets arm64 on client side

**Comment by alexellis** [comment]
Hi @yunfan, can I help you with the problem you saw?

Alex

**Comment by yunfan** [comment]
@alexellis  thanks
here is my problem below in the picture

![image](https://paste.ubuntu.org.cn/i4384021)

https://paste.ubuntu.org.cn/i4384021

there're 4 pane in the window,  each i labeled with a red capital letter in ABCD

A is my vps side
B is my machine side
C is my internal service
D is the shell showing show i use that 

unfortunated you could see the tunnel hasnt work
OR had i use the tunnel in a wrong way?

**Comment by alexellis** [comment]
![i4384021](https://user-images.githubusercontent.com/6358735/57482275-2738a880-729c-11e9-87c9-a46c15f9c0f4.png)

For anyone who couldn't load the link (insecure / invalid TLS)

**Comment by alexellis** [comment]
What version is this? Are you using the auth token?

**Comment by yunfan** [comment]
@alexellis      its the latest version whilei post the issue  and i havnt use auth token

**Comment by yunfan** [comment]
@alexellis   on my local machine side its

```
Version: 2.0.2
Git Commit: 317007726fe2af458780cbd30831cc7ddcafeb7b
```

on my vps side its
```
Version: 2.0.0
Git Commit: 44bb61cb9b1488042d01f7fd4fa24f7d347e558f
```

**Comment by alexellis** [comment]
Hi, I think the PR #53 by @ibuildthecloud introduced a regression for this feature.

#63 should fix this, but I can't merge until the PR gets signed-off by the author.

I'll ping you when that's done, if you want to try a manual build the patch is:

```
diff --git a/pkg/router/router.go b/pkg/router/router.go
index ce7f3d6..c005f8d 100644
--- a/pkg/router/router.go
+++ b/pkg/router/router.go
@@ -48,7 +48,7 @@ func (r *Router) Lookup(req *http.Request) *Route {
        r.RLock()
        defer r.RUnlock()
 
-       targets := r.domains[req.URL.Host]
+       targets := r.domains[req.Host]
        if len(targets) == 0 {
                targets = r.domains[""]
        }
```

**Comment by yunfan** [comment]
@alexellis thanks, i saw the pr has been aproved, and my problem should be solved now, but still i hope you could add a `--verbose` option to enable debuging infos

**Comment by alexellis** [comment]
There is a new release that you can pick up now. It should resolve this problem. 

They used to be very verbose logging until we switched over the implementation to use remote dialler from Darren. 

What specific information would you like to see?

**Comment by yunfan** [comment]
@alexellis yep it has solved that, thanks for the helpful tool

i just want it acts like debug mode enabling while using that option, so i could see everything that helps instead of post random issues :D

**Comment by alexellis** [comment]
👍 

Thanks
