### ISSUE TITLE
client:"panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by blackzw** [alexellis/inlets#65]
server: 
1. system: ubuntu 18.04 
2. install with :" curl -sLS https://get.inlets.dev | sudo sh"
3. run inlets with: " inlets server --port=18989"
4. console output: " Listening on :18989"

client: 
1. system: mac x
2. install with: " brew install inlets"
3. run inlets client with: "inlets client -r <my_remote_server>:18989 -u 127.0.0.1:18990"
4. console output:
> 2019/05/12 22:05:29 Upstream:  => 127.0.0.1:18990
2019/05/12 22:05:29 connecting to ws://<my_remote_server>:18989/tunnel with ping=10s
2019/05/12 22:05:30 Ping duration: 10.000000s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130822b]

>goroutine 1 [running]:
github.com/alexellis/inlets/vendor/github.com/gorilla/websocket.(*Conn).SetReadDeadline(...)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/vendor/github.com/gorilla/websocket/conn.go:1041
github.com/alexellis/inlets/pkg/transport.(*WebsocketConn).setupDeadline(0xc000180090)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/pkg/transport/pingpong.go:37 +0xfb
github.com/alexellis/inlets/pkg/transport.NewWebsocketConn(...)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/pkg/transport/pingpong.go:23
github.com/alexellis/inlets/pkg/client.(*Client).Connect(0xc0000d2f00, 0x0, 0x0)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/pkg/client/client.go:62 +0x487
github.com/alexellis/inlets/cmd.runClient(0x17db560, 0xc0000e4540, 0x0, 0x4, 0x0, 0x0)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/cmd/client.go:99 +0x39c
github.com/alexellis/inlets/vendor/github.com/spf13/cobra.(*Command).execute(0x17db560, 0xc0000e44c0, 0x4, 0x4, 0x17db560, 0xc0000e44c0)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/alexellis/inlets/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17db7c0, 0x2, 0x1471cfe, 0x1c)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/alexellis/inlets/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/vendor/github.com/spf13/cobra/command.go:800
github.com/alexellis/inlets/cmd.Execute(0x14eb378, 0x5, 0x14fd700, 0x28, 0xc0000f9f88, 0xc000092058)
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/cmd/inlets.go:50 +0x78
main.main()
	/private/tmp/inlets-20190418-79973-19tg2uq/src/github.com/alexellis/inlets/main.go:14 +0x51

and server console output:
> http: multiple response.WriteHeader calls

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* inlets version `inlets --version` 
client:
> Version: 0.6.3
Git Commit: 01b26ba23791041121e4996609c96cfa4e25bf64

server:
> Version: 2.0.3
Git Commit: fc8ffa2067ae3a7751bc6ad9434c2186502469f7

* Docker/Kubernetes version `docker version` / `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Please try the version from curl/sh.

**Comment by alexellis** [comment]
I can't see your upstream flag which is required. Have you read how it works in the readme?

**Comment by alexellis** [comment]
The version in `brew` is incompatible with the latest version. We may need to remove the instructions to use `brew` temporarily. 

Please see also: #66 

Can you test again using the `curl` approach on both ends of the tunnel?

cc @rgee0 could you edit the README?

Alex

**Comment by alexellis** [comment]
Seems I jumped the gun on that. Brew does now have 2.0 available 🎉 

No need to remove the option. #66 can also be closed.
