### ISSUE TITLE
Unable to Serve Multiple Upstreams

### ISSUE THREAD

**Issue by schuermannator** [alexellis/inlets#67]
In the client, HTTP headers are set such that subsequent upstream endpoints are overwritten, meaning you cannot have multiple upstream endpoints (the only one that functions is the last one passed in). 

## Expected Behaviour
Expected to append (add) multiple upstreams to the HTTP headers.

## Current Behaviour
Overwrites the `X-Inlets-Upstream` in headers to single upstream (the last one passed in your command line args, since it just overwrites for each).

## Possible Solution
I've come up with the small change, just changing the `header.Set()` to `header.Add()`. I'm opening a PR to fix! The header was set using `header.Set()` which led to overriding the headers for multiple upstreams, such that only the last one in the `--upstream` arguments is present in the header upstream. Tested and it successfully prints the headers with multiple upstreams and serves both.

## Steps to Reproduce (for bugs)
Run inlet client with multiple `--upstream` arguments. They successfully print, and thus are stored in the map correctly, i.e.
```
2019/06/05 13:29:17 Upstream: test.example.com => http://127.0.0.1:12435
2019/06/05 13:29:17 Upstream: test2.example.com => http://127.0.0.1:54321
```
but when the headers are printed, only one is included:
```
map[X-Inlets-Id:[XXXXXXXXXXXXXXXXXXXXXX] X-Inlets-Upstream:
[test2.example.com=http://127.0.0.1:54321] Authorization:[Bearer XXXXXXXXXXXXXXX]]
```

## Context
Trying to use inlets to provide ingress control for kubernetes cluster. Followed the "will it cluster" article about k3s, and wanting support for reaching multiple services with inlets.

## Your Environment

* inlets version `2.0.3` 

* Docker version 
```Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

* Operating System and version: `Linux 4.15.0-50-generic #54-Ubuntu SMP x86_64 GNU/Linux`

**Comment by alexellis** [comment]
Thank you for writing up a detailed report. 

This definitely worked pre 2.0 where we merged a change from @ibuildthecloud to use w library for the tunnels instead of my original code.

**Comment by schuermannator** [comment]
Thanks, it's a simple fix I believe. I've tested locally. Let me know if I need to do anything else for testing or if I signed correctly etc.

**Comment by alexellis** [comment]
Derek close: issue fixed by linked PR
