### ISSUE TITLE
Feature request: build with Go modules

### ISSUE THREAD

**Issue by Thor77** [alexellis/inlets#69]
## Current Behaviour
Everyone wanting to build the project is forced to install and use `dep`.

## Possible Solution
Switch to [go modules](https://github.com/golang/go/wiki/Modules).

If this get's approval from a maintainer, I could open a PR implementing that change.

**Comment by alexellis** [comment]
You don't need to install dep to build the project and nothing is forced upon you? What's the perceived problem with dep?

Alex

**Comment by alexellis** [comment]
Derek set title: Feature request: build with Go modules

**Comment by Thor77** [comment]
> What's the perceived problem with dep?
It requires a `$GOPATH` setup.

**Comment by alexellis** [comment]
I'm not going to move to go modules at this time and will close the issue, but it will remain in the history for tracking. I may change my mind in the near future, but right now all the OSS projects I'm maintaining use `dep` and will continue to do so until I can test and move them all over in one go.

Right now it's not a blocking problem, just a nice-to-have for some developers.

In light of this I'd suggest setting your `GOPATH` then, or using the Docker image to do your builds.
