### ISSUE TITLE
Switch from go/flags to Cobra

### ISSUE THREAD

**Issue by alexellis** [alexellis/inlets#7]
Move from the Golang flags package for the CLI options to Cobra.

Example/more details:

https://blog.alexellis.io/5-keys-to-a-killer-go-cli/

openfaas/faas-cli is a good sample to follow, or alexellis/jaas which is much smaller.

-server=true/false would become a sub-command along with client

```
inlets server --port
inlets client --port --remote / -r
```

The changes should also cover the README.md / instructions.

Use `git commit -s` for commits.

**Comment by RaviTezu** [comment]
@alexellis I would like to take this unless someone is already working on it.

**Comment by alexellis** [comment]
Thanks perhaps we need to merge #12 first?

**Comment by alexellis** [comment]
@RaviTezu please go ahead and raise your PR 👍 

See the contributing guide too on how to sign-off commits with `git commit --sign-off`.

**Comment by RaviTezu** [comment]
Thanks @alexellis I will start on this.

**Comment by alexellis** [comment]
Awesome, please see how it was done for the OpenFaaS CLI https://github.com/openfaas/faas-cli
