### ISSUE TITLE
Option to keep CORS headers in the response

### ISSUE THREAD

**Issue by rycus86** [alexellis/inlets#75]
We have noticed that CORS related headers, like `Access-Control-Allow-Origin`, are stripped out of the responses. When investigating, I found that the `k8s.io/apimachinery/pkg/util/proxy` package's `NewUpgradeAwareHandler` does this on purpose, when the `wrapTransport` parameter is set to `true` - as is here in inlets.

## Expected Behaviour

Our use-case would require keeping the CORS headers.

## Current Behaviour

CORS headers are missing in the response coming back from the inlets server.

## Possible Solution

Internally, we patched the latest inlets master to include a new server argument, `--disable-transport-wrapping`, that is off by default but when enabled, asks the proxy utility code to __not__ wrap the transport and therefore keep the CORS headers. So far it's working fine, didn't find anything broken by this change, so I'd be happy to upstream it.

## Your Environment

Tested with inlets `2.1.0`

Let me know if you'd be open to having a flag like this, and I'll create a pull request.
Thank you!

**Comment by alexellis** [comment]
Thank you for your issue and I'm glad inlets is proving useful for you. 

Please send the PR and add documentation for the flag.

Alex

**Comment by neoakris** [comment]
@rycus86 @alexellis 
I'll soon be posting an article that mentions using inlets with nginx ingress controller, I'd like to suggest readers use this flag, but before suggesting such a thing I'm curious if there are security considerations to disabling transport wrapping.  
I'll keep googling but the keywords are generic + it's niche knowledge which makes it difficult to google for an answer. + I'm not a WebSockets expert so I don't have enough contextual knowledge to even understanding what's happening when the flag is off/on.

**Comment by rycus86** [comment]
Hi @neoakris
I think this is the PR that introduced the change: https://github.com/kubernetes/kubernetes/pull/9159
From that, it looks like to me that it's not about legacy clients, but more about trying to default misbehaving pods into not ever serving CORS headers - which is usually not what we'd want here with inlets.

I agree it would make a sensible default for inlets, not sure what backwards compatibility issues would it surface though for others.
