### ISSUE TITLE
can not import inlets package

### ISSUE THREAD

**Issue by coderafei** [alexellis/inlets#76]
build error
## Expected Behaviour
build pass

## Current Behaviour
not enough arguments in call to remotedialer.ClientConnect
	have (string, http.Header, nil, func(string, string) bool, nil)
	want (context.Context, string, http.Header, *websocket.Dialer, remotedialer.ConnectAuthorizer, func(context.Context) error)

## Possible Solution
fix the params

## Steps to Reproduce (for bugs)
```go
import (
	"fmt"
	"log"
	"strings"

	"github.com/alexellis/inlets/pkg/client"
)
...
inletsClient := client.Client{
		Remote: "127.0.0.1:8089",
		UpstreamMap:upstreamMap,
		Token: "",
}

if err := inletsClient.Connect(); err != nil {
	log.Printf("Err: %v", err)
}
```

## Your Environment
go 1.12 with go modules

* inlets version `inlets --version` 
latest master

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

**Comment by coderafei** [comment]
https://github.com/rancher/remotedialer/pull/2
https://github.com/rancher/remotedialer/pull/3

**Comment by alexellis** [comment]
Hi, we are not using Go modules with this project, but dep. That probably means that you are pointing at a version of the remotedialer that is newer than is tested with inlets.

This isn't an issue with inlets.

You could:

- use dep
- continue with Go modules and pin the correct version as defined in Gopkg.toml
- or propose a PR using dep to update to the version in HEAD that you are using 

Alex
