### ISSUE TITLE
Ubuntu 16.04 - Error connecting client "http: multiple response.WriteHeader calls"

### ISSUE THREAD

**Issue by dougnukem** [alexellis/inlets#79]
When running through the examples on a local machine I'm getting an error ( "http: multiple response.WriteHeader calls") when trying to connect the `inlets client`

Running the following services:
```shell
# inlets server
$ inlets server --port=8091 --token="$token"
```
```shell
# Local hash-browns service
$ go get github.com/alexellis/hash-browns
$ port=3001 hash-browns

# inlets client
 inlets client \
 --remote=127.0.0.1:8091 \
 --upstream=http://127.0.0.1:3001
 --token $TOKEN
```

## Expected Behaviour
The inlets client is able to connect with the server.

## Current Behaviour
The client and server return errors when connect.

Client errors:
```shell
$ inlets client \
 --remote=127.0.0.1:8091 \
 --upstream=http://127.0.0.1:3001
 --token $TOKEN
2019/08/10 20:26:23 Upstream:  => http://127.0.0.1:3001
map[X-Inlets-Id:[xxxx] X-Inlets-Upstream:[=http://127.0.0.1:3001]]
INFO[0000] Connecting to proxy                           url="ws://127.0.0.1:8091/tunnel"
ERRO[0000] Failed to connect to proxy                    error="websocket: bad handshake"
ERRO[0000] Failed to connect to proxy                    error="websocket: bad handshake"
```

The server error is:
```shell
$ inlets server --port=8091 --token="$token"
2019/08/10 20:25:42 Server token: "xxxx"
2019/08/10 20:25:42 Listening on :8091
2019/08/10 20:26:23 http: multiple response.WriteHeader calls
2019/08/10 20:26:28 http: multiple response.WriteHeader calls
```

## Your Environment

* inlets version `inlets --version` 

I'm running the following versions on client server installed from:
```shell
$ curl -sLS https://get.inlets.dev | sudo sh
$ inlets -v
Version: 2.2.0
Git Commit: 2f5e458d062e55dda9f08109f7b2c3c6919fcdf9
```

I've also tried installing from latest using `go get` and still get the same error:
```shell
$  go get -u github.com/alexellis/inlets
$ inlets -v
Version: dev
Git Commit:
```
- OS: Linux 
   - Also tried Mac OSX as inlets client on same network, same error

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

```
$  go version
go version go1.11 linux/amd64
```

**Comment by dougnukem** [comment]
It does appear to work correctly when run entirely on Mac OSX, and

- Mac OSX: `inlets server`
- Linux (Ubuntu 16.04): `inlets client` 


But it fails when any client tries to onnect to:
- Linux (Ubuntu 16.04): `inlets server` (`go -v go1.11`)

**Comment by dougnukem** [comment]
I think I found the issue....

It appears the docs were missing a trailing `/` before the `--token=xyz` so it was never passing that in for the client.

**Comment by alexellis** [comment]
Glad you found the issue. Thank you for the PR!
