### ISSUE TITLE
[Question] Is Basic Auth stripped out?

### ISSUE THREAD

**Issue by tomkelsey** [alexellis/inlets#91]
Hey,

This project looks really interesting! Hope it's okay to ask a question here?

I have a raspberry pi connected to the internet via a 4G sim card.

The raspberry pi is running a proxy server that's protected by basic auth.

If the raspberry pi had it's own public IP I'd utilise the proxy server by way of URL e.g.

http://username:password@public-ip:port

Unfortunately it's behind what I understand to be "carrier grade NAT" and so I'm trying to use inlets to make it publicly accessible.

I've installed and run inlets on a publicly hosted server and the client on the raspberry pi and I believe I've been able to connect them.

I'm therefore using this as my proxy server URL:

http://username:password@public-ip-of-inlets-server:port

However, I'm getting issues with the basic auth not being passed through to the raspberry pi. I was wondering if by using inlets this is somehow stripped out or if I need to look elsewhere for my problem?

I’m a little out of my depth with all of this so apologies if this is a bonkers/stupid question :)

**Comment by alexellis** [comment]
Hi there,

Thanks for th question. The answer is that I wouldn't have thought so given that OpenFaaS was tested and works when punched out with inlets.

I don't know if we've had any regression, but I'd expect it to still work. 

Can you share an example of how we can try to reproduce this? 

Alex

**Comment by alexellis** [comment]
@tomkelsey please look at my response from just over a week ago now.

**Comment by alexellis** [comment]
![Screenshot from 2019-09-08 08-52-37](https://user-images.githubusercontent.com/6358735/64485237-09615d00-d216-11e9-8682-76cdba9e59f6.png)
![Screenshot from 2019-09-08 08-52-20](https://user-images.githubusercontent.com/6358735/64485238-09615d00-d216-11e9-8bbd-5c652e38824e.png)

No issues forwarding OpenFaaS from my Intel NUC.

I'll close this issue. Please let me know if you need further help

**Comment by tomkelsey** [comment]
Hi @alexellis,

Thanks for getting back to me and apologies for not following up.

I haven't had a chance yet to re-visit the issue but it looks like you've ruled out Basic Auth being an issue so thank you very much indeed for your help.

**Comment by securisec** [comment]
@alexellis Sorry to bring up an old issue, but i am running into this also. I am running inlets behind Traefik with a basic auth middleware, and am getting a 401 also. I tried setting the username and password as part of the wss remote url, with and without stripping the basic auth header, but cant seem to get it to work. Any suggestions?

**Comment by alexellis** [comment]
@securisec I see you deleted your comment?

>@alexellis Sorry to bring up an old issue, but i am running into this also. I am running inlets behind Traefik with a basic auth middleware, and am getting a 401 also. I tried setting the username and password as part of the wss remote url, with and without stripping the basic auth header, but cant seem to get it to work. Any suggestions?

I guess you got it working? :-)

By the way, you should take a look at inlets PRO which has built-in TLS termination, and can expose Traefik itself, making it much easier to integrate to your infrastructure.
